// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWebApp.DataAccess.Context;

namespace TestWebApp.DataAccess.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250711182853_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWebApp.Entities.User", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("usuId")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<string>("lastName")
                        .HasColumnName("apellido")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("name")
                        .HasColumnName("nombre")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            lastName = "Pérez",
                            name = "Juan"
                        },
                        new
                        {
                            Id = 2m,
                            lastName = "García",
                            name = "Ana"
                        },
                        new
                        {
                            Id = 3m,
                            lastName = "Martínez",
                            name = "Luis"
                        },
                        new
                        {
                            Id = 4m,
                            lastName = "López",
                            name = "María"
                        },
                        new
                        {
                            Id = 5m,
                            lastName = "Ramírez",
                            name = "Carlos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
